import type { Brand } from '../types'
import { aurelCollections } from './collections'
import { aurelProducts } from './products'
import { aurelReviews } from './reviews'

export const aurelBrand: Brand = {
  id: 'aurel',
  name: 'AUREL',
  tagline: 'Skincare, considered.',
  description:
    'A contemporary skincare house focused on simple, highly considered formulations and refined daily rituals.',
  category: 'Skincare',
  typography: {
    display: '"Cormorant Garamond", "Times New Roman", serif',
    body: '"Manrope", "Helvetica Neue", sans-serif',
    ui: '"Manrope", "Helvetica Neue", sans-serif',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,500;0,600;1,500&family=Manrope:wght@400;500;600&display=swap',
    tracking: {
      display: '-0.018em',
      heading: '-0.015em',
      body: '0',
      eyebrow: '0.22em',
      nav: '0.18em',
      button: '0.18em',
      logo: '0.42em',
      meta: '0.14em',
    },
    transform: {
      eyebrow: 'uppercase',
      nav: 'uppercase',
      button: 'uppercase',
      logo: 'uppercase',
    },
  },
  colors: {
    background: '#F3EEE6',
    surface: '#E8E0D4',
    ink: '#2A241C',
    muted: '#74685C',
    accent: '#8A5A3C',
    line: '#D4CBBE',
    inverse: '#F7F3EC',
  },
  shape: {
    radiusSm: '0px',
    radiusMd: '0px',
    radiusLg: '0px',
    radiusFull: '999px',
    borderWidth: '1px',
    shadow: 'none',
    shadowRaised: 'none',
  },
  density: 'regular',
  buttons: {
    radius: 'sm',
    shadow: false,
    px: '1.5rem',
    py: '0.75rem',
  },
  media: {
    productRatio: 'portrait',
    editorialRatio: 'wide',
    storyRatio: 'tall',
  },
  productCard: {
    align: 'left',
    ratio: 'portrait',
    hoverScale: 1.03,
    hoverSwap: true,
    showRating: false,
    showQuickAdd: false,
    showSwatches: true,
    showCategory: false,
    titlePrice: 'row',
    elevated: false,
  },
  copy: {
    addToCart: 'Add to ritual',
    quickAdd: 'Quick add',
    account: 'Account',
    search: 'Search',
    cart: 'Bag',
    menu: 'Menu',
  },
  header: {
    logoPosition: 'center',
    splitNav: true,
    showSearch: true,
    showAccount: true,
    showCart: true,
    accountHref: '/about',
    desktopNavFrom: 'xl',
    sticky: true,
    blur: true,
    bordered: true,
    elevated: false,
  },
  logoText: 'AUREL',
  announcement: 'Complimentary linen pouch on orders over $150',
  navigation: [
    { label: 'Shop', href: '/collections/all' },
    { label: 'Collections', href: '/collections/essentials' },
    { label: 'Our Philosophy', href: '/about' },
    { label: 'Journal', href: '/about' },
  ],
  secondaryNav: [],
  photography: {
    hero: '/brands/aurel/hero.webp',
    editorial01: '/brands/aurel/editorial-01.webp',
    editorial02: '/brands/aurel/editorial-02.webp',
    editorial03: '/brands/aurel/editorial-03.webp',
    editorial04: '/brands/aurel/editorial-04.webp',
    philosophy: '/brands/aurel/philosophy.webp',
    formulation: '/brands/aurel/formulation.webp',
    story: '/brands/aurel/story.webp',
    about: '/brands/aurel/about.webp',
    marquee: '/brands/aurel/editorial-01.webp',
  },
  products: aurelProducts,
  collections: aurelCollections,
  homepage: {
    sections: [
      {
        type: 'hero',
        eyebrow: 'The daily ritual',
        heading: 'Skincare, considered.',
        subheading:
          'Essential formulations designed to simplify the everyday ritual of caring for your skin.',
        ctaLabel: 'Shop skincare',
        ctaHref: '/collections/all',
        ctaSecondaryLabel: 'Discover AUREL',
        ctaSecondaryHref: '/about',
        image: '/brands/aurel/hero.webp',
        imageAlt: 'Editorial still life of AUREL skincare in warm window light',
        layout: 'split',
      },
      {
        type: 'featured',
        heading: 'Considered essentials.',
        subheading: 'A focused collection of formulations designed to become part of your everyday.',
        productIds: [
          'aureole-vitamin-c',
          'lumen-cleansing-milk',
          'cloud-barrier-cream',
          'night-restore',
        ],
        ctaLabel: 'View all products',
        ctaHref: '/collections/all',
      },
      {
        type: 'editorial',
        eyebrow: 'Our approach',
        heading: 'Less, but better.',
        body: 'AUREL is built around the belief that an effective routine does not need to be complicated. We create considered formulations, refined textures and purposeful essentials designed to earn their place in your daily ritual.',
        image: '/brands/aurel/philosophy.webp',
        imageAlt: 'Stone table, linen and afternoon light in a quiet interior',
      },
      {
        type: 'imageText',
        eyebrow: 'Formulated with intent',
        heading: 'Every ingredient has a reason.',
        body: 'From texture to absorption, every detail is considered. AUREL formulations bring together carefully selected active ingredients with a sensorial experience designed for everyday use.',
        image: '/brands/aurel/formulation.webp',
        imageAlt: 'AUREL formulations arranged with glassware on limestone',
        reverse: true,
        headingVariant: 'h2',
        ctaLabel: 'Explore our philosophy',
        ctaHref: '/about',
      },
      {
        type: 'ritual',
        heading: 'A ritual in three steps.',
        steps: [
          {
            number: '01',
            title: 'Cleanse',
            productId: 'lumen-cleansing-milk',
            body: 'Begin with a milky cleanse that lifts the day without asking the skin to tighten.',
            ctaLabel: 'Shop cleanser',
            image: '/brands/aurel/ritual-cleanse.webp',
            imageAlt: 'The Daily Cleanser on stone beside running water',
          },
          {
            number: '02',
            title: 'Treat',
            productId: 'aureole-vitamin-c',
            body: 'A few drops of serum, pressed in. Brightness as a habit, not a performance.',
            ctaLabel: 'Shop serum',
            image: '/brands/aurel/ritual-treat.webp',
            imageAlt: 'The Renewal Serum with dropper lifted over stone',
          },
          {
            number: '03',
            title: 'Restore',
            productId: 'cloud-barrier-cream',
            body: 'Seal the ritual with a cream that disappears, then stays — skin left quiet, not coated.',
            ctaLabel: 'Shop cream',
            image: '/brands/aurel/ritual-restore.webp',
            imageAlt: 'The Barrier Cream on stone in evening light',
          },
        ],
      },
      {
        type: 'trust',
        heading: 'Formulation, without the noise.',
        items: [
          {
            title: 'Purposeful ingredients',
            body: 'Every ingredient is selected for a reason.',
          },
          {
            title: 'Considered textures',
            body: 'Formulations designed to feel as good as they perform.',
          },
          {
            title: 'Everyday efficacy',
            body: 'Effective skincare designed for real routines.',
          },
        ],
      },
      {
        type: 'reviews',
        heading: 'Part of the ritual.',
        showStars: false,
      },
      {
        type: 'imageGrid',
        images: [
          {
            src: '/brands/aurel/editorial-01.webp',
            alt: 'Hands and linen in an AUREL lifestyle frame',
            size: 'large',
          },
          {
            src: '/brands/aurel/editorial-02.webp',
            alt: 'Close study of an AUREL bottle',
            size: 'tall',
          },
          {
            src: '/brands/aurel/editorial-03.webp',
            alt: 'Texture and surface detail from the cabinet',
            size: 'wide',
          },
          {
            src: '/brands/aurel/editorial-04.webp',
            alt: 'Arched plaster opening toward hills at dusk',
            size: 'default',
          },
        ],
      },
      {
        type: 'newsletter',
        eyebrow: 'The AUREL Journal',
        heading: 'Notes on skin, ritual and considered living.',
        body: 'Occasional notes from AUREL. New formulations, rituals and stories.',
        placeholder: 'Email address',
        ctaLabel: 'Subscribe',
      },
    ],
  },
  socialProof: aurelReviews,
  brandStory: {
    eyebrow: 'Our philosophy',
    heading: 'Less, but better.',
    paragraphs: [
      'AUREL is built around the belief that an effective routine does not need to be complicated. We create considered formulations, refined textures and purposeful essentials designed to earn their place in your daily ritual.',
      'Quiet luxury, for us, is not beige for its own sake. It is the decision to print a ritual card instead of a manifesto, to offer a cream refill instead of a new jar, to photograph skin in window light instead of a ring light.',
      'If a formula needs a warning label longer than its benefit, it does not belong here. If it layers with the rest of the line on a weekday, it does.',
    ],
    image: '/brands/aurel/philosophy.webp',
    imageAlt: 'AUREL studio table with glass, linen and warm light',
    values: [
      {
        title: 'Purposeful ingredients',
        body: 'Every ingredient is selected for a reason — texture, absorption, and the way it lives on skin.',
      },
      {
        title: 'Considered textures',
        body: 'Formulations designed to feel as good as they perform, from the first pump to the last.',
      },
      {
        title: 'Everyday efficacy',
        body: 'Effective skincare designed for real routines, not a fifteen-step calendar.',
      },
    ],
  },
  footer: {
    blurb: 'AUREL — considered formulations for a quieter daily ritual.',
    columns: [
      {
        title: 'Shop',
        links: [
          { label: 'All Products', href: '/collections/all' },
          { label: 'Best Sellers', href: '/collections/essentials' },
          { label: 'Collections', href: '/collections/essentials' },
        ],
      },
      {
        title: 'About',
        links: [
          { label: 'Our Philosophy', href: '/about' },
          { label: 'Journal', href: '/about' },
          { label: 'Contact', href: '/about' },
        ],
      },
      {
        title: 'Support',
        links: [
          { label: 'Shipping', href: '/about' },
          { label: 'Returns', href: '/about' },
          { label: 'FAQ', href: '/about' },
        ],
      },
      {
        title: 'Social',
        links: [
          { label: 'Instagram', href: 'https://instagram.com' },
          { label: 'Pinterest', href: 'https://pinterest.com' },
        ],
      },
    ],
    social: [],
    legal: [
      { label: 'Privacy', href: '/about' },
      { label: 'Terms', href: '/about' },
      { label: 'Accessibility', href: '/about' },
    ],
    payments: ['Visa', 'Mastercard', 'Amex'],
    copyright: '© 2026 AUREL. All rights reserved.',
  },
  searchPlaceholder: 'Search formulations, rituals…',
}
