import type { Review } from '../types'

export const aurelReviews: Review[] = [
  {
    id: 'r1',
    productId: 'aureole-vitamin-c',
    author: 'Mira K.',
    location: 'Lisbon',
    rating: 5,
    title: 'Brightness without the lecture',
    body: 'I have abandoned more vitamin C serums than I will admit. Aureole is the first that does not sting and still, after six weeks, my winter dullness has somewhere to go. The dropper is honest — three drops is actually three drops.',
    date: 'March 2026',
  },
  {
    id: 'r2',
    productId: 'cloud-barrier-cream',
    author: 'Helen P.',
    location: 'Chicago',
    rating: 5,
    title: 'The cream I take through winter',
    body: 'Radiators ruin me. Cloud Barrier does not sit on the surface like a wax. It disappears and then, hours later, my cheeks have not asked for more. The refill pod made me loyal.',
    date: 'January 2026',
  },
  {
    id: 'r3',
    productId: 'lumen-cleansing-milk',
    author: 'Jonah R.',
    location: 'Portland',
    rating: 5,
    title: 'Finally a cleanse that is not a debate',
    body: 'I wear mineral SPF every day. Lumen takes it off without the squeak. I use the 200 ml because the 100 disappeared too quickly, which is a compliment.',
    date: 'February 2026',
  },
  {
    id: 'r4',
    productId: 'night-restore',
    author: 'Asha N.',
    location: 'London',
    rating: 4,
    title: 'Rested, not retouched',
    body: 'Bakuchiol is quieter than the retinoid I used to bully my skin with. Texture along my jaw has softened. It is an oil, so I use four drops, not six. More than that and I shine.',
    date: 'December 2025',
  },
  {
    id: 'r5',
    productId: 'mineral-silk-spf',
    author: 'Priya S.',
    location: 'Austin',
    rating: 5,
    title: 'No ghost, no grease',
    body: 'I am medium-deep and most mineral screens chalk me. This one blends to a silk I can live in. Two fingers is the right amount — one is optimism.',
    date: 'April 2026',
  },
  {
    id: 'r6',
    productId: 'dawn-ritual-set',
    author: 'Elena V.',
    location: 'Milan',
    rating: 5,
    title: 'The cabinet, decided',
    body: 'I stopped assembling a routine from five different brands. The card in the box is better than most blogs. Everything layers. Nothing pills. I reordered the cream refill first.',
    date: 'May 2026',
  },
]
